dataset:
  train:
    path: data/objaverse/train
    sort_by: zyx
  eval:
    path: data/objaverse/eval
    sort_by: zyx

collate_fn:
  vertex_padding_value: 0.0
  face_padding_value: 0
  edge_padding_value: 0

optimizer:
  lr: 1e-4
  betas: [0.9, 0.99]

scheduler:
  lr_min: 1e-7

train:
  num_epochs: 2
  per_device_batch_size: 8
